SPLIT_KEYBOARD = yes
SERIAL_DRIVER = usart

AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_ENABLE = no
OLED_ENABLE = no
OLED_DRIVER = SSD1306
ENCODER_ENABLE = no
LTO_ENABLE = no

EXTRAFLAGS += -flto
